services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fitplans_user
      - POSTGRES_PASSWORD=fitplans_password
      - POSTGRES_DB=fitplans_db

  redis:
    image: redis:7-alpine

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    command: celery flower --broker=redis://redis:6379/0 --port=5555 --basic_auth=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
  static_volume:
  media_volume:
