# Generated by Django 5.2.3 on 2025-12-12 09:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Начинающий'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый')], default='BEGINNER', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='plan_covers/')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликован'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='plans.category')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='trainers.trainer')),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='plan_files/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Видео'), ('IMAGE', 'Изображение')], default='PDF', max_length=20)),
                ('is_preview', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='plans.plan')),
            ],
            options={
                'db_table': 'plan_files',
                'ordering': ['order'],
            },
        ),
    ]
